### PR TITLE
Update run script to version 0.3.2

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Updated the run script to the latest version

## QA
- Pull branch
- Run `./run` and check it works
- Run `./run watch` and make a change and see it changes
- Run `./run clean` and see it cleans

### CODE REVIEW

**Comment by barrymcgee** [comment]
@anthonydillon I'm getting a 404 for your fork? https://github.com/anthonydillon/cloud-init.io/

**Comment by deadlight** [comment]
@barrymcgee his fork is just called `cloud-init`. I'll review this as it's holding up a release.

**Comment by barrymcgee** [comment]
Odd - I thought all forks were named the same as upstream repo.

**Comment by anthonydillon** [comment]
I must have forked before the upstream we renamed.

**Pull request merged**
